from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = ...
    apellido = ...
    nacionalidad = ...
    lugar_de_nacimeinto = ...
    fecha_de_nacimiento = ...
    