# Generated by Django 4.1.2 on 2022-10-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatFormulario',
            new_name='Chat',
        ),
    ]
