# Generated by Django 4.1.2 on 2022-11-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
