# Generated by Django 4.1.2 on 2022-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
