# Generated by Django 4.1.2 on 2022-11-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='apellido',
        ),
    ]
