# Generated by Django 4.1.2 on 2022-11-10 18:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_de_creacion', models.DateTimeField(auto_now=True)),
                ('chat', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
