# Generated by Django 4.1.2 on 2022-11-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
