# Generated by Django 4.1.2 on 2022-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
