# Generated by Django 4.1.2 on 2022-11-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_extensionusuario_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionusuario',
            name='link',
        ),
    ]
