# Generated by Django 4.1.2 on 2022-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugar_de_nacimiento', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('equipo_actual', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
