# Generated by Django 4.1.2 on 2022-10-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_jugador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
