# Generated by Django 4.1.2 on 2022-10-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_de_nacimiento',
            field=models.DateField(help_text='MM/DD/AAAA'),
        ),
    ]
