# Generated by Django 4.1.2 on 2022-11-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_jugador_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='imagen',
        ),
    ]
